### ISSUE TITLE
你好，冒昧想请教一下，你博客里面使用的字体加载方案是？

### ISSUE THREAD

**Issue by fedkwan** [mebtte/article#6]
在v2ex看到你的博客，点进去，觉得字体很好看，而且加载速度很快，想知道是使用了什么加载方案呢？

**Comment by mebtte** [comment]
使用了 `fontmin` 这个库做字体子集化, 所以字体文件会很小, 具体实现可以看一下 `scripts` 下的代码, 或者查看我之前的文章 [基于 Node.js 的 WebFont 解决方案](https://article.mebtte.com/web_font_solution_by_node)
![image](https://user-images.githubusercontent.com/8120967/99030444-01d2dc00-25b0-11eb-8dc5-e0411c9be23d.png)
