### ISSUE TITLE
请教一下，articles目录下的文章已经删了，但依旧出现已经删除的文章

### ISSUE THREAD

**Issue by WilliamsZhang** [mebtte/article#7]

**Comment by mebtte** [comment]
删掉后有重新构建吗?

**Comment by WilliamsZhang** [comment]
> 删掉后有重新构建吗?

有在本地构建，我在本地构建是成功的，删掉的文章都没有了，但上传到GitHub还是存在，是上传到GitHub之后还要进行什么操作吗？

**Comment by mebtte** [comment]
你的github workflows没有重新执行

**Comment by mebtte** [comment]
github pages托管的是gh-pages分支上的资源, 要让workflows重新执行或者手动推送构建后的资源到这个分支

**Comment by WilliamsZhang** [comment]
> 你的github workflows没有重新执行

感谢，之前没用过GitHub的这个功能，现在构建成功了
